### ISSUE TITLE
Hosted trial for company is handled

### ISSUE THREAD

**Issue by guylabs** [guylabs/project-test#9]
## Prospect details

* Company: company
* Email: email@email.com
* Trial expiry date: 2018-06-22

## Hosted trial environment details

Use the following details when provisioning the GE trial instance:

* Public license id: `trialPublicLicenseId`
* AWS region: `awsRegion`
* GE instance username: `geUsername`
* GE instance password: `gePassword`

## Tasks
Ensure all tasks are addressed in each stage of the hosted trial process. If one of the TeamCity jobs fails, read this document [here](https://github.com/gradle/dotcom/blob/master/docs/reference/operations/hosted-trial-provision-decommission-failures.md) for advice.

### 1. Provision the hosted trial environment

- [ ] 1. Reply to the email on the engineering mailing list to let the team know you are handling the hosted trial request.
- [ ] 2. Assign the issue to yourself.
- [ ] 3. Provision an AWS instance using this [TeamCity job](https://builds.gradle.org/viewType.html?buildTypeId=Enterprise_Operations_HostedTrials_Create). Use the details provided in the environment details section above.

### 2. Decommission the hosted trial environment

- [ ] 4. Delete and shut down the AWS instance using this [TeamCity job](https://builds.gradle.org/viewType.html?buildTypeId=Enterprise_Operations_HostedTrials_Destroy).
